Vagrant.configure(2) do |config|
    config.vm.define "node1.example.com" do |node1|
        node1.vm.box = "centos/7"
        node1.vm.network "forwarded_port", guest: 80, host: 8081
        node1.vm.network :forwarded_port, guest: 22, host: 2221, auto_correct: false, id: "ssh"
    end
end

