- name: Install epel repository 
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'
 
- name: Install packages (CentOS only)
  yum: name='{{ item }}' state=present
  with_items: '{{ install_packages }}'
  when: ansible_distribution == 'CentOS'

