- name: Installing Epel-release package (CentOS only)
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

- name: Installing required packages (RedHat based only)
  yum: name='{{ item }}' state=present
  with_items: '{{ install_packages }}'
  when: ansible_os_family == 'RedHat' 

- name: Installing required packages (Debian based only)
  apt: name='{{ item }}' state=present
  with_items: '{{ install_packages }}'
  when: ansible_os_family == 'Debian' 

