Vagrant.configure(2) do |config|
    config.vm.define "node1" do |node1|
        node1.vm.box = "centos/7"
        node1.vm.network "private_network", ip: "192.168.2.11"
        node1.vm.network :forwarded_port, guest: 22, host: 2221, auto_correct: false, id: "ssh"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "centos/7"
        node2.vm.network "private_network", ip: "192.168.2.12"
        node2.vm.network :forwarded_port, guest: 22, host: 2222, auto_correct: false, id: "ssh"
    end
    config.vm.define "node3" do |node3|
        node3.vm.box = "ubuntu/xenial64"
        node3.vm.network "private_network", ip: "192.168.2.13"
        node3.vm.network :forwarded_port, guest: 22, host: 2223, auto_correct: false, id: "ssh"
    end
end

