Vagrant.configure(2) do |config|
    config.vm.define "node1" do |node1|
        node1.vm.box = "centos/7"
        node1.vm.network "private_network", ip: "192.168.2.11"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "centos/7"
        node2.vm.network "private_network", ip: "192.168.2.12"
    end
    config.vm.define "node3" do |node3|
        node3.vm.box = "ubuntu/xenial64"
        node3.vm.network "private_network", ip: "192.168.2.13"
    end
end

