Vagrant.configure(2) do |config|
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    config.vm.define "www1.example.com" do |www|
        www.vm.box = "centos/7"
        www.vm.network "private_network", ip: "192.168.1.1"
    end
    config.vm.define "www2.example.com" do |www|
        www.vm.box = "centos/7"
        www.vm.network "private_network", ip: "192.168.1.2"
    end
    config.vm.define "lb.example.com" do |lb|
        lb.vm.box = "ubuntu/xenial64"
        lb.vm.network "private_network", ip: "192.168.1.3"
        lb.vm.provision "shell",
          inline: "sudo apt install -y python-minimal"
    end
end

