- hosts: all
  become: yes
  tasks:
  - name: Loading variables from external file
    include_vars: vars1.yml

  - name: Creating the devops account
    user: 
      comment: '{{ devops_comment }}'
      createhome: '{{ devops_createhome }}'
      name: '{{ devops_login }}'

  - name: Define a dynamic variable
    set_fact: 
      var1: This is a dynamic variable var1
      var2: This is a dynamic variable var2

  - name: Debug output of the var1
    debug: msg='{{ var1 }}'

  - name: Debug output of the var2
    debug: msg='{{ var2 }}'


