- hosts: all
  become: yes
  vars:
    users_node1: [ 'user1', 'user2', 'user3' ]
    users_node2: [ 'devops1', 'devops2', 'devops3' ]
  tasks:
    - name: Create users on node1.example.com
      user: name='{{ item }}'
      when: inventory_hostname == 'node1.example.com'
      with_items: '{{ users_node1 }}'

    - name: Create users on node2.example.com
      user: name='{{ item }}'
      when: inventory_hostname == 'node2.example.com'
      with_items: '{{ users_node2 }}'



