- hosts: all
  become: yes
  vars:
    users: [ 'user1', 'user2', 'user3' ]
  tasks:
    - name: Create users on node1.example.com
      user: name='{{ item }}'
      when: inventory_hostname == 'node1.example.com'

    - name: Create users on node1.example.com if its OS is RedHat based
      user: name='{{ item }}'
      when: inventory_hostname == 'node1.example.com' and ansible_os_family == 'RedHat'

