- hosts: all
  become: yes
  vars:
    users: user4
  tasks:
    - name: Create users on node1.example.com if its OS is RedHat based
      user: name='{{ users }}'
      when: inventory_hostname == 'node1.example.com' and ansible_os_family == 'RedHat'

