- hosts: node2.example.com
  become: yes
  gather_facts: yes
  tasks:
    - name: Set correct hostname
      hostname: name='{{ inventory_hostname }}'

    - name: Adding own IP address into /etc/hosts file
      lineinfile: 
        path: /etc/hosts
        regexp: "^{{ ansible_eth0['ipv4']['address'] }}.*$"
        line: "{{ ansible_eth0['ipv4']['address'] }} {{ inventory_hostname }}"

    - name: Install tcpdump package (CentOS only)
      yum: name='tcpdump' state=installed
      when: ansible_distribution == 'CentOS'


