- hosts: node1.example.com
  become: yes
  tasks:
    - name: Installing packages
      yum: name='{{ item }}'
      with_items:
      - wget
      - git
      - tcpdump
      when: ansible_distribution == 'CentOS'

