Vagrant.configure(2) do |config|
    config.vm.define "node1.example.com" do |node1|
        node1.vm.box = "centos/7"
        node1.vm.network :forwarded_port, guest: 22, host: 2221, auto_correct: false, id: "ssh"
        node1.vm.network "forwarded_port", guest: 80, host: 8081, protocol: "tcp"

    end
    config.vm.define "node2.example.com" do |node2|
        node2.vm.box = "centos/7"
        node2.vm.network :forwarded_port, guest: 22, host: 2222, auto_correct: false, id: "ssh"
        node2.vm.network "forwarded_port", guest: 80, host: 8082, protocol: "tcp"

    end
end

